<?php

namespace Database\Seeders;

use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countryarray = [
            "American Samoa",
            "Andorra",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Bermuda",
            "Bhutan",
            "Bolivia, Plurinational State of",
            "Bonaire, Sint Eustatius and Saba",
            "Bosnia and Herzegovina",
            "Bouvet Island",
            "Brazil",
            "Brunei Darussalam",
            "Bulgaria",
            "Cameroon",
            "Canada",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Cook Islands",
            "Costa Rica",
            "Croatia",
            "Curaçao",
            "Cyprus",
            "Czechia",
            "Denmark",
            "Djibouti",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Estonia",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "Georgia",
            "Germany",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guyana",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kiribati",
            "Korea, Republic of",
            "Kuwait",
            "Kyrgyzstan",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao",
            "Malaysia",
            "Maldives",
            "Marshall Islands",
            "Martinique",
            "Mauritius",
            "Mexico",
            "Micronesia, Federated States of",
            "Moldova, Republic of",
            "Monaco",
            "Montenegro",
            "Montserrat",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Caledonia",
            "New Zealand",
            "Niger",
            "Norfolk Island",
            "Northern Mariana Islands",
            "North Macedonia",
            "Norway",
            "Oman",
            "Palau",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Romania",
            "Russian Federation",
            "Saint Barthélemy",
            "Saint Helena, Ascension and Tristan da Cunha",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Martin (French part)",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Saudi Arabia",
            "Serbia",
            "Singapore",
            "Sint Maarten (Dutch part)",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "South Africa",
            "Spain",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Taiwan, Province of China",
            "Tajikistan",
            "Thailand",
            "Tonga",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom of Great Britain and Northern Ireland",
            "United States of America",
            "United States Minor Outlying Islands",
            "Uruguay",
            "Uzbekistan",
            "Venezuela, Bolivarian Republic of",
            "Viet Nam",
            "Virgin Islands, British",
            "Virgin Islands, U.S.",
        ];
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('countries')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $faker = Faker::create();
        $allData = $countryarray;

        foreach ($allData as $key => $value) {
            $insertData[$key] = array(
                'uuid' => $faker->uuid(),
                'country_name' => $value,
                'created_at' => $faker->date('Y-m-d H:m:s'),
                'updated_at' => $faker->date('Y-m-d H:m:s'),

            );
        }
        DB::table('countries')->insert($insertData);
    }
}
